name: Beta Release

on:
  push:
    branches:
      - 'main'
    paths:
      - '**'
      - '!README.md'
      - '!doc/**'
      - '!.github/workflows/**'
  workflow_dispatch:

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run: Compile'
        run: ./build.cmd Compile
        env:
          NuGetApiKey: ${{ secrets.NUGET_API_KEY }}
          NuGetFeed: ${{ secrets.NUGET_FEED }}
          PackAndPublish: true
      - name: 'Save test reports'
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: artifacts/test-reports